### ISSUE TITLE
Use logos from CfAPI

### ISSUE THREAD

**Issue by ondrae** [Code-for-All/codeforall.org-concept-2017#15]
Once [logos are added](https://github.com/codeforamerica/cfapi/issues/166) to the CfAPI, use them instead of the hard coded versions we have now.

**Comment by ondrae** [comment]
Code for Germany and Code for Caribbean logo's got deleted?

**Comment by KrzysztofMadejski** [comment]
If we have logos we will commit them directly to the repo.
