### ISSUE TITLE
Code for All site requirements

### ISSUE THREAD

**Issue by cdaloisio** [Code-for-All/codeforall.org-concept-2017#3]
Here's a proposal of site requirements based on the goals:

**1. Show off the collected activities of the Code for All network.**
- Use a statically defined list of Code for All partners to then use cfAPI to:
  - get list of projects
  - get list of issues
  - get list of events

**2. Promote the work of the Code for All partners.**
- Use an RSS feed aggregator (such as http://selfoss.aditu.de/) to combine all 'Code for' feeds from cfAPI
- We can also add separate feeds to this aggregator if we wish

**3. Host tools needed by the network.**
- No additional tools required at the moment (apart from RSS aggregator)

Please discuss so we can adjust and then confirm the requirements.

**Comment by ondrae** [comment]
Okay the updates have been made to our API to show just Code for All groups.
[http://codeforamerica.org/api/organizations?type=Code for All](http://codeforamerica.org/api/organizations?type=Code%20for%20All)

Works for projects as well. Not Stories, Events, or Issues yet though.
[http://codeforamerica.org/api/projects?organization_type=Code for All](http://codeforamerica.org/api/projects?organization_type=Code%20for%20All)

**Comment by hoony-o-1** [comment]
great updates. these would be so useful to build a website of codeforall.

**Comment by ondrae** [comment]
I did few updates. Check it out.

New icons and popups
New stats from the API
New recent projects, events, and stories

**Comment by cdaloisio** [comment]
Looks great. I'll have a chance to add a few things next week - I've been away on leave :)

**Comment by cdaloisio** [comment]
I made some updates also, have a look in #5 for the details.
