### ISSUE TITLE
https certificate reported as insecure

### ISSUE THREAD

**Issue by milovanderlinden** [Code-for-All/codeforall.org-concept-2017#32]
My browser reports the api endpoint for https://api.codeforamerica.org/api/organizations.geojson as insecure. I do need it however for https://code-for-all.github.io/codeforall.org/chapters to show the map.

**Comment by jgroenen** [comment]
I asked in the CfA slack if the api.... is maintained because ssl is invalid. Waiting for response.

**Comment by milovanderlinden** [comment]
Any update on this?

**Comment by milovanderlinden** [comment]
For now I am using a local copy. This copy contains some enhancements. We need to ask Code For America to migrate our local changes back before changing the url.

**Comment by milovanderlinden** [comment]
No longer needed as we are now a http website.

**Comment by KrzysztofMadejski** [comment]
My two browsers don't complain about the certificate.
