### ISSUE TITLE
Page: Partners

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Code-for-All/codeforall.org-concept-2017#35]
- [x] rename "chapters" to "partners"
- [x] map
- [ ] list of partners
  - name
  - country (flag)
  - organization logo (maybe? may pollute visually)
  - link to the website
  - status (governing / affiliate) - tag or an icon
- [x] at the bottom info about partnerships
  - How do I join?
    - Governing partner -> READ MORE
    - Affiliate partner -> READ MORE

Questions:
- how do we present donors? -> ON, NED
- how do we present strategic partners, such as NDI? 

Looking at current version of https://codefornl.github.io/codeforall.org/chapters/:
- drop mission statements and all links except for the one to the main website
- move here links to more detailed information about joining

**Comment by milovanderlinden** [comment]
I have renamed chapters to partners, can you scratch that of the list?

**Comment by milovanderlinden** [comment]
This issue needs to be split up as it is to big to fix in one commit.

**Comment by milovanderlinden** [comment]
Updated the checkmarks

**Comment by KrzysztofMadejski** [comment]
I've broken it into smaller issues:
- #46 
- #45 
- #44
