### ISSUE TITLE
subPage: Governing partner

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Code-for-All/codeforall.org-concept-2017#36]
who is a governing partners, how to become one?
Linked from #35 

Copy: from https://codeforall.org/becoming-a-partner/:
- Governing Partners
- Process for Consideration of New Governing Partners
- Partnership Committee
- + "Feel that you are ready to upgrade from Affiliate to Governing Partner status? Talk to us."

**Comment by milovanderlinden** [comment]
Set up a first draft, please review.

**Comment by KrzysztofMadejski** [comment]
Looks great!
