### ISSUE TITLE
Remove Code For NL Fork

### ISSUE THREAD

**Issue by milovanderlinden** [Code-for-All/codeforall.org-concept-2017#40]
As we now have direct access to this repository, it is no longer required to pull to https://github.com/codefornl/codeforall.org @jgroenen is it ok if we set our local upstream to https://github.com/code-for-all/codeforall.org and remove this repository?

**Comment by jgroenen** [comment]
Yes, of course :)

**Comment by milovanderlinden** [comment]
Done
