### ISSUE TITLE
How to fit  Civic Issue Finder ?

### ISSUE THREAD

**Issue by KrzysztofMadejski** [Code-for-All/codeforall.org-concept-2017#47]
@milovanderlinden wrote on #38
- - - 
There is another version of the Civic Issue Finder over at https://helpwanted.team/ Its meant to make it easier to get help on certain Github Issues that you choose. The content gets updated with issues labeled help wanted.

@ondrae set an environment up for Code for All https://helpwanted.team/code-for-all

Maybe this can be integrated into projects/resources?

**Comment by KrzysztofMadejski** [comment]
I see it on more on the Get Involved page

**Comment by milovanderlinden** [comment]
For now I have added a button for help wanted on the Projects page.
