### ISSUE TITLE
Add social buttons to footer

### ISSUE THREAD

**Issue by milovanderlinden** [Code-for-All/codeforall.org-concept-2017#53]
In the footer, add buttons for:
- [Facebook](https://www.facebook.com/letscodeforall/)
- [Twitter](https://twitter.com/CodeforAll)
- [Youtube](https://www.youtube.com/channel/UCWD9S7drnf6v74YimdmlX1A)
- [Medium](https://medium.com/code-for-all)
- [Email](mailto://info@codeforall.org)

**Comment by KrzysztofMadejski** [comment]
I don't see it anywhere.

**Comment by milovanderlinden** [comment]
Please look at the bottom of each page; the buttons should be there:
![screenshot-2018-2-16 code for all](https://user-images.githubusercontent.com/106038/36327242-47cd0c92-135e-11e8-8040-e3ba97f72777.png)

**Comment by KrzysztofMadejski** [comment]
Sorry, that was my adblock.
